# Generated by Django 3.2.3 on 2021-06-04 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_auto_20210602_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={'verbose_name': 'Friendship', 'verbose_name_plural': 'Friendships'},
        ),
    ]
