# Generated by Django 3.2.3 on 2021-06-07 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
